### ISSUE TITLE
Identify audience for website and create personas

### ISSUE THREAD

**Issue by nielseny** [hackforla/YouthJusticeNav#18]
### Overview
We need to know who we are designing this website for

### Action Items

- [x] Review the one sheet and pull out all the audience types and put in this issue
- [x] Identify audiences we have not named
- [x] Review with Bonnie
- [ ] Review with UCLA Law School
- [ ] Create personas from validated user groups

### Resources/Instructions
- [UCLA Docs](https://github.com/hackforla/YouthJusticeNav/projects/1#card-52056008)

**Comment by ltung05** [comment]
**Personas:**
- Youth Defendant
  - As a youth defendant, I should be able to understand my rights while using this website/app.
- Family/Caregivers
  - As a family member/caregiver of the defendant, I should be able to find out the resources available to me in order to help my child.
- Public Defender
  - As a public defender of the defendant, I should able to use this website/app to help the defendant to navigate the youth justice system with ease.
- Law Enforcement Officials
  - As a law enforcement official, I should be able to know beforehand what was explained to the defendant to ensure a smooth proceeding of hearings.

**Comment by ltung05** [comment]
@ltung05 to create google documentation with the information above

**Comment by ExperimentsInHonesty** [comment]
@ltung05 I created the doc with the above info in it, because I want to use it in a meeting tomorrow https://docs.google.com/document/d/1u_i1EPeO7Y9upUYoFWDAZLQz1G8d8XNBn1W6PILznF0/edit#
